noticeably update bash_utils and scripts which depend on them

diff --git a/.bin/mnt b/.bin/mnt
--- a/.bin/mnt
+++ b/.bin/mnt
@@ -29,106 +29,70 @@
 # Pull in variables
 [ "$1" ] && [ -e "$1" ] && . "$1"
 
-log () {
-  # Log to file or stdout
-  echo "$@"
-  [ "$logfile" ] && echo "$(date) - $(basename $0) - $@" >> "$logfile"
+. bash_utils
+
+mnt_smb() {
+	# Mount a share via smb
+	password="$(rawurlencode "${password}")"
+	url="${url:-//${user}:${password}@${server}/${path}}"
+
+	mount | grep -q "$mountpoint" ||
+		for i in {1..20}; do
+			if ping -c 1 "${server}"; then
+				mkdir -p "${mountpoint}"
+				log "Attempting to mount (${server}/${share}) at (${mountpoint})..."
+				log mount_smbfs "${url:-//${user}:********@${server}/${path}}" "${mountpoint}"
+				mount_smbfs "${url}" "${mountpoint}"
+				log "Return code: $?"
+				break
+			fi
+			[ $i = 20 ] && exit 1
+		done
 }
 
-exe () {
-	# Display and execute the command
-  log 2>&1 "\$ $*"
-  "$@" 2>&1
-}
+mnt_smb_ssh() {
+	# Mount a share via smb through an ssh tunnel
+	localhost="${localhost:-127.0.0.2}"
+	port_forward_string="${port_forward_string:-${localhost}:445:${fileserver}:445}"
+	url="//${user}@${localhost}/${path}"
+	socket="${socket:-/tmp/mnt_smb_ssh.sock}"
 
-# https://gist.github.com/jaytaylor/6527607
-timeout() {
-  # kill the command if not finished in $1 seconds
-  perl -e 'alarm shift; exec @ARGV' "$@";
-}
+	. "$HOME/.bin/start-ssh-agent"
 
-# https://stackoverflow.com/questions/296536/how-to-urlencode-data-for-curl-command
-rawurlencode() {
-  # URL-encode a string
-  local string="${1}"
-  local strlen=${#string}
-  local encoded=""
-  local pos c o
+	password="$(rawurlencode "${password}")"
 
-  for (( pos=0 ; pos<strlen ; pos++ )); do
-     c=${string:$pos:1}
-     case "$c" in
-        [-_.~a-zA-Z0-9] ) o="${c}" ;;
-        * )               printf -v o '%%%02x' "'$c"
-     esac
-     encoded+="${o}"
-  done
-  echo "${encoded}"    # You can either set a return variable (FASTER)
-  # REPLY="${encoded}"   #+or echo the result (EASIER)... or both... :p
-}
-
-mnt_smb () {
-  # Mount a share via smb
-  password="$(rawurlencode "${password}")"
-  url="${url:-//${user}:${password}@${server}/${path}}"
-
-  mount | grep -q "$mountpoint" || \
-    for i in {1..20}; do
-      if ping -c 1 "${server}"; then
-        mkdir -p "${mountpoint}"
-        log "Attempting to mount (${server}/${share}) at (${mountpoint})..."
-        log mount_smbfs "${url:-//${user}:********@${server}/${path}}" "${mountpoint}"
-        mount_smbfs "${url}" "${mountpoint}"
-        log "Return code: $?"
-        break
-      fi
-      [ $i = 20 ] && exit 1
-    done
-}
-
-mnt_smb_ssh () {
-  # Mount a share via smb through an ssh tunnel
-  localhost="${localhost:-127.0.0.2}"
-  port_forward_string="${port_forward_string:-${localhost}:445:${fileserver}:445}"
-  url="//${user}@${localhost}/${path}"
-  socket="${socket:-/tmp/mnt_smb_ssh.sock}"
-  
-  . "$HOME/.bin/start-ssh-agent"
-
-  password="$(rawurlencode "${password}")"
-
-  if mount | grep -q "${mountpoint}"; then
-    echo "A volume is already mounted at (${mountpoint})"
-    exit 0
-  else
-    log "Attempting to mount (${fileserver}/${path}) via ssh tunnel at (${mountpoint})..."
-    mkdir -p "${mountpoint}"
-    for i in {1..20}; do
-      if timeout 1 bash -c "echo > /dev/tcp/${sshhost}/${sshport}" >/dev/null 2>&1; then
-        echo "${sudo_password}" | \
-          exe sudo -S ifconfig lo0 ${localhost} alias up
-        log "Return code: $?"
-        sleep 1
-        log sudo -S ssh -fNM -i ${ssh_identity_file} -p "${sshport}" -S "${socket}" -L "${port_forward_string}" "${user}@${sshhost}"
-        echo "${sudo_password}" | \
-          { nohup sudo -S ssh -fNM -i ${ssh_identity_file} -p "${sshport}" -S "${socket}" -L "${port_forward_string}" "${user}@${sshhost}" </dev/null >/dev/null 2>&1 & } &
-        log "Return code: $?"
-        log mount_smbfs "//${user}:********@${localhost}/${path}" "${mountpoint}"
-        mount_smbfs "//${user}:${password}@${localhost}/${path}" "${mountpoint}"
-        err=$?
-        log "Return code: $err"
-        exit $err
-      else
-        log "Waiting for ${sshhost} to become available on ${sshport}"
-      fi
-    done
-    log "failed."
-    exit ${sshport}
-  fi
+	if mount | grep -q "${mountpoint}"; then
+		echo "A volume is already mounted at (${mountpoint})"
+		exit 0
+	else
+		log "Attempting to mount (${fileserver}/${path}) via ssh tunnel at (${mountpoint})..."
+		mkdir -p "${mountpoint}"
+		for i in {1..20}; do
+			if timeout 1 bash -c "echo > /dev/tcp/${sshhost}/${sshport}" >/dev/null 2>&1; then
+				echo "${sudo_password}" |
+					exe sudo -S ifconfig lo0 ${localhost} alias up
+				log "Return code: $?"
+				sleep 1
+				log sudo -S ssh -fNM -i ${ssh_identity_file} -p "${sshport}" -S "${socket}" -L "${port_forward_string}" "${user}@${sshhost}"
+				echo "${sudo_password}" |
+					{ nohup sudo -S ssh -fNM -i ${ssh_identity_file} -p "${sshport}" -S "${socket}" -L "${port_forward_string}" "${user}@${sshhost}" </dev/null >/dev/null 2>&1 &;} &
+				log "Return code: $?"
+				log mount_smbfs "//${user}:********@${localhost}/${path}" "${mountpoint}"
+				mount_smbfs "//${user}:${password}@${localhost}/${path}" "${mountpoint}"
+				err=$?
+				log "Return code: $err"
+				exit $err
+			else
+				log "Waiting for ${sshhost} to become available on ${sshport}"
+			fi
+		done
+		log "failed."
+		exit ${sshport}
+	fi
 }
 
 case $type in
-  smb) mnt_smb ;;
-  smb-over-ssh) mnt_smb_ssh ;;
-  *) echo "Error. Unsupported type. See comments in `mnt` for details"
+smb) mnt_smb ;;
+smb-over-ssh) mnt_smb_ssh ;;
+*) echo "Error. Unsupported type. See comments in $(mnt) for details" ;;
 esac
