update scripts

diff --git a/.bin/sudo_mnt b/.bin/sudo_mnt
--- a/.bin/sudo_mnt
+++ b/.bin/sudo_mnt
@@ -29,103 +29,101 @@
 # Pull in variables
 [ "$1" ] && [ -e "$1" ] && . "$1"
 
-log () {
-  # Log to file or stdout
-  echo "$@"
-  [ "$logfile" ] && echo "$(date) - $(basename $0) - $@" >> "$logfile"
+log() {
+	# Log to file or stdout
+	echo "$@"
+	[ "$logfile" ] && echo "$(date) - $(basename $0) - $@" >>"$logfile"
 }
 
-exe () {
+exe() {
 	# Display and execute the command
-  log 2>&1 "\$ $*"
-  "$@" 2>&1
+	log 2>&1 "\$ $*"
+	"$@" 2>&1
 }
 
 # https://gist.github.com/jaytaylor/6527607
 timeout() {
-  # kill the command if not finished in $1 seconds
-  perl -e 'alarm shift; exec @ARGV' "$@";
+	# kill the command if not finished in $1 seconds
+	perl -e 'alarm shift; exec @ARGV' "$@"
 }
 
 # https://stackoverflow.com/questions/296536/how-to-urlencode-data-for-curl-command
 rawurlencode() {
-  # URL-encode a string
-  local string="${1}"
-  local strlen=${#string}
-  local encoded=""
-  local pos c o
+	# URL-encode a string
+	local string="${1}"
+	local strlen=${#string}
+	local encoded=""
+	local pos c o
 
-  for (( pos=0 ; pos<strlen ; pos++ )); do
-     c=${string:$pos:1}
-     case "$c" in
-        [-_.~a-zA-Z0-9] ) o="${c}" ;;
-        * )               printf -v o '%%%02x' "'$c"
-     esac
-     encoded+="${o}"
-  done
-  echo "${encoded}"    # You can either set a return variable (FASTER)
-  # REPLY="${encoded}"   #+or echo the result (EASIER)... or both... :p
+	for ((pos = 0; pos < strlen; pos++)); do
+		c=${string:$pos:1}
+		case "$c" in
+		[-_.~a-zA-Z0-9]) o="${c}" ;;
+		*) printf -v o '%%%02x' "'$c" ;;
+		esac
+		encoded+="${o}"
+	done
+	echo "${encoded}" # You can either set a return variable (FASTER)
+	# REPLY="${encoded}"   #+or echo the result (EASIER)... or both... :p
 }
 
-mnt_smb () {
-  # Mount a share via smb
-  password="$(rawurlencode "${password}")"
-  url="${url:-//${user}:${password}@${server}/${path}}"
+mnt_smb() {
+	# Mount a share via smb
+	password="$(rawurlencode "${password}")"
+	url="${url:-//${user}:${password}@${server}/${path}}"
 
-  mount | grep -q "$mountpoint" || \
-    for i in {1..20}; do
-      if ping -c 1 "${server}"; then
-        mkdir -p "${mountpoint}"
-        log "Attempting to mount (${server}/${share}) at (${mountpoint})..."
-        log mount_smbfs "//${user}:********@${server}/${path}" "${mountpoint}"
-        mount_smbfs "${url}" "${mountpoint}"
-        log "Return code: $?"
-        break
-      fi
-      [ $i = 20 ] && exit 1
-    done
+	mount | grep -q "$mountpoint" ||
+		for i in {1..20}; do
+			if ping -c 1 "${server}"; then
+				mkdir -p "${mountpoint}"
+				log "Attempting to mount (${server}/${share}) at (${mountpoint})..."
+				log mount_smbfs "//${user}:********@${server}/${path}" "${mountpoint}"
+				mount_smbfs "${url}" "${mountpoint}"
+				log "Return code: $?"
+				break
+			fi
+			[ $i = 20 ] && exit 1
+		done
 }
 
-mnt_smb_ssh () {
-  # Mount a share via smb through an ssh tunnel
-  localhost="${localhost:-127.0.0.2}"
-  port_forward_string="${port_forward_string:-${localhost}:445:${fileserver}:445}"
-  url="//${user}@${localhost}/${path}"
-  socket="${socket:-/tmp/mnt_smb_ssh.sock}"
-  
-  . "$HOME/.bin/start-ssh-agent"
+mnt_smb_ssh() {
+	# Mount a share via smb through an ssh tunnel
+	localhost="${localhost:-127.0.0.2}"
+	port_forward_string="${port_forward_string:-${localhost}:445:${fileserver}:445}"
+	url="//${user}@${localhost}/${path}"
+	socket="${socket:-/tmp/mnt_smb_ssh.sock}"
 
-  password="$(rawurlencode "${password}")"
+	password="$(rawurlencode "${password}")"
 
-  if mount | grep -q "${mountpoint}"; then
-    echo "A volume is already mounted at (${mountpoint})"
-    exit 0
-  else
-    log "Attempting to mount (${fileserver}/${path}) via ssh tunnel at (${mountpoint})..."
-    for i in {1..20}; do
-      if timeout 1 bash -c "echo > /dev/tcp/${sshhost}/${sshport}" >/dev/null 2>&1; then
-        exe sudo ifconfig lo0 ${localhost} alias up
-        log "Return code: $?"
-        sleep 1
-        log sudo ssh -fNM -i ${ssh_identity_file} -p "${sshport}" -S "${socket}" -L "${port_forward_string}" "${user}@${sshhost}"
-        sudo ssh -fNM -i ${ssh_identity_file} -p "${sshport}" -S "${socket}" -L "${port_forward_string}" "${user}@${sshhost}"
-        log "Return code: $?"
-        log mount_smbfs "//${user}:********@${localhost}/${path}" "${mountpoint}"
-        mount_smbfs "//${user}:${password}@${localhost}/${path}" "${mountpoint}"
-        err=$?
-        log "Return code: $err"
-        exit $err
-      else
-        log "Waiting for ${sshhost} to become available on ${sshport}"
-      fi
-    done
-    log "failed."
-    exit ${sshport}
-  fi
+	if mount | grep -q "${mountpoint}"; then
+		echo "A volume is already mounted at (${mountpoint})"
+		exit 0
+	else
+		log "Attempting to mount (${fileserver}/${path}) via ssh tunnel at (${mountpoint})..."
+		for i in {1..20}; do
+			if timeout 1 bash -c "echo > /dev/tcp/${sshhost}/${sshport}" >/dev/null 2>&1; then
+				exe sudo ifconfig lo0 ${localhost} alias up
+				log "Return code: $?"
+				sleep 1
+				log sudo ssh -fNM -i ${ssh_identity_file} -p "${sshport}" -S "${socket}" -L "${port_forward_string}" "${user}@${sshhost}"
+				sudo ssh -fNM -i ${ssh_identity_file} -p "${sshport}" -S "${socket}" -L "${port_forward_string}" "${user}@${sshhost}"
+				log "Return code: $?"
+				log mount_smbfs "//${user}:********@${localhost}/${path}" "${mountpoint}"
+				mount_smbfs "//${user}:${password}@${localhost}/${path}" "${mountpoint}"
+				err=$?
+				log "Return code: $err"
+				exit $err
+			else
+				log "Waiting for ${sshhost} to become available on ${sshport}"
+			fi
+		done
+		log "failed."
+		exit ${sshport}
+	fi
 }
 
 case $type in
-  smb) mnt_smb ;;
-  smb-over-ssh) mnt_smb_ssh ;;
-  *) echo "Error. Unsupported type. See comments in `mnt` for details"
+smb) mnt_smb ;;
+smb-over-ssh) mnt_smb_ssh ;;
+*) echo "Error. Unsupported type. See comments in $(mnt) for details" ;;
 esac
