mild update-* scripts improvements

diff --git a/.bin/update-macos b/.bin/update-macos
--- a/.bin/update-macos
+++ b/.bin/update-macos
@@ -1,3 +1,7 @@
 #!/usr/bin/env bash
 
-sudo xcode-select --install 2&>1 || echo The Xcode Command Line Tools package is already installed
+if [ "$(uname)" = "Darwin" ]; then
+	sudo xcode-select --install 2 &>1 || echo The Xcode Command Line Tools package is already installed
+else
+	echo "macos not found, skipping"
+fi
